CREATE TABLE IF NOT EXISTS classes (
	code TEXT PRIMARY KEY,
	faculty TEXT NOT NULL DEFAULT '',
	academic_year TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);